version: '3.8'
services:
  shipapi:
    image: ${DOCKER_REGISTRY-}shipapi
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
      - "80:80"
      - "443:443"
  frontend:
    image: ship-management-frontend
    build:
      context: ./ClientApp
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - shipapi
